use MyShopDB;

-- 1. Write an SQL query to find out which customers have not placed any orders.

SELECT FirstName, LastName, Email
FROM Customers c
WHERE NOT EXISTS (
    SELECT 1
    FROM Orders o
    WHERE o.CustomerID = c.CustomerID
    
);

-- 2. SQL query to find the total number of products available for sale:

SELECT COUNT(*) AS TotalProducts
FROM Products;

-- 3. SQL query to calculate the total revenue generated by TechShop:

SELECT SUM(od.Quantity * p.Price) AS TotalRevenue
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID;

-- 4. SQL query to calculate the average quantity ordered for products in a specific category:

DECLARE @CategoryName NVARCHAR(255);
SET @CategoryName = '';  

SELECT AVG(od.Quantity) AS AverageQuantityOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
WHERE p.Description LIKE '%' + @CategoryName + '%';

-- 5. SQL query to calculate the total revenue generated by a specific customer:

DECLARE @CustomerID INT;
SET @CustomerID = 3; 

SELECT SUM(od.Quantity * p.Price) AS TotalRevenue
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
WHERE o.CustomerID = @CustomerID;

-- 6. SQL query to find the customers who have placed the most orders:

SELECT c.FirstName, c.LastName, COUNT(o.OrderID) AS OrderCount
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.FirstName, c.LastName
ORDER BY OrderCount DESC;